### ISSUE TITLE
Failed to find regions

### ISSUE THREAD

**Issue by EnriqueBanderas** [Electronics/F1NameChanger#10]
![113521117-bb4e4000-9597-11eb-8ff2-a5f919936ab5](https://user-images.githubusercontent.com/81928959/113554469-abffde80-95f9-11eb-9ba5-df1e20720d52.png)

I thought about creating a separare issue for this, regions are not detected. Ran in admin mode, happens both on Dx11 and 12, game is updated to 1.17. Thank you in advance for any help, if you need something else please ask

**Comment by driverman123** [comment]
also the case for me.

![Screenshot_13](https://user-images.githubusercontent.com/81973272/113582185-bb4e4e80-9630-11eb-8bcb-9d6e398f086d.png)

**Comment by Electronics** [comment]
Are you on the english version of the game?

**Comment by driverman123** [comment]
yea

**Comment by Electronics** [comment]
If you know anything about cheat engine, could you search for the following strings and tell me / screenshot their offsets?
`{o:mixed}Carlos`
`{o:mixed}Daniel`
`RIVER].bk2`

**Comment by driverman123** [comment]
i searched the strings, not sure how to see offsets. can you help?

**Comment by EnriqueBanderas** [comment]
I have Cheat Engine installed and if guided I think I can tell you what you need to know...

**Comment by Electronics** [comment]
If you could just search for those strings, and then screenshot the left-side pane where it's discovered all the matching bits in ram, that would be most helpful whilst I download the other languages for F1 2020

**Comment by driverman123** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/81973272/113763576-7dc9ee00-9722-11eb-91e5-8059ca2e5432.png)
like this you mean?

**Comment by BBence3450** [comment]
That's my problem, too

**Comment by Electronics** [comment]
> 
> 
> ![Screenshot_19](https://user-images.githubusercontent.com/81973272/113763576-7dc9ee00-9722-11eb-91e5-8059ca2e5432.png)
> like this you mean?

Yes! If you could do the same for the other strings that would be awesome.

**Comment by driverman123** [comment]
![Screenshot_21](https://user-images.githubusercontent.com/81973272/113907546-2e48f800-97de-11eb-967a-8e40a8a8253c.png)
![Screenshot_22](https://user-images.githubusercontent.com/81973272/113907548-2f7a2500-97de-11eb-9c17-dd6a0727d04e.png)
there you go dude :)

**Comment by EnriqueBanderas** [comment]
Hello, I just did the same, with DirectX11 playing. Hope it may help!

![carlos](https://user-images.githubusercontent.com/81928959/113908246-9a276280-97d6-11eb-8c5b-5c36828c5185.PNG)

![daniel](https://user-images.githubusercontent.com/81928959/113908266-9eec1680-97d6-11eb-8d45-cf91d0c0c160.PNG)

![river](https://user-images.githubusercontent.com/81928959/113908280-a3b0ca80-97d6-11eb-9cab-da4b63d26b41.PNG)

**Comment by Electronics** [comment]
I believe I've just got a new version working. It now doesn't rely on my statically coded offsets for searching through small bits of RAM. Instead it searches the entire memory of the game for the regions I'm interested in and then moves on from there.

Just doing some testing and updating of the UI...

**Comment by driverman123** [comment]
awesome! will test as soon as possible.

**Comment by driverman123** [comment]
Working! Thank you so much.

**Comment by EnriqueBanderas** [comment]
Did not realize a new version was released. I will test it as soon as possible and will let you know, in case it work may I close the issue?

**Comment by EnriqueBanderas** [comment]
Working! You are my hero!
