### ISSUE TITLE
Stuck editing region 1

### ISSUE THREAD

**Issue by db19891** [Electronics/F1NameChanger#11]
Apologies if this is just an issue on my end.

The lookup gets stuck editing region 1 for me. I have verified game files and tried with names files other users know work. I play the game in English.

Thanks.
![Screenshot 2021-04-06 225801](https://user-images.githubusercontent.com/60779115/114197437-40e04000-994a-11eb-9d5f-83280b4f541d.png)

**Comment by Electronics** [comment]
Try running the tool as administrator? It might be your windows security settings prevent the tool from editing the game's memory.
