### ISSUE TITLE
The Names are not changing permanently.

### ISSUE THREAD

**Issue by kalpakpdoshi** [Electronics/F1NameChanger#16]
I have to open the program everytime I start F1 2020 and then find offsets everytime and then Run the Program everytime I start the game.
Any solutions?

**Comment by Electronics** [comment]
The tool is designed to be run every time the game is started afresh, however `find offsets` should only need to be run once per game update. When ran again the tool should prompt you to "Would you like to use the custom offsets?" in which case you should click yes, as those will be the offsets found from before.
