### ISSUE TITLE
Latest patch/update causing error

### ISSUE THREAD

**Issue by StormNoack** [Electronics/F1NameChanger#19]
Please see race department regarding the error that most of us are currently experiencing due to the latest change in F1 2020 files. Finding offsets does not work. It would be amazing if you could help the community by looking at this problem and fixing it. Thank you.

**Comment by mg1519** [comment]
Really hope he sees this

**Comment by werrer612** [comment]
should we ping him so that he can see the message above?

**Comment by StormNoack** [comment]
Think we should. @Electronics

**Comment by Electronics** [comment]
Oh hello, hm I'll try to have a look at this. I wonder what's changed...

**Comment by StormNoack** [comment]
That would be amazing! Thank you @Electronics

**Comment by werrer612** [comment]
thank you so much

**Comment by StormNoack** [comment]
@Electronics Any update on this yet?

**Comment by mg1519** [comment]
@Electronics Thank you man! hope for a fix at some point, it's an incredible mod!

**Comment by franpr42** [comment]
> 
> 
> Oh hello, hm I'll try to have a look at this. I wonder what's changed...

@Electronics, Codemasters removed Denuvo DRM protection in the latest patch. Perhaps that's what is causing the issue. Also [this user in RaceDepartment](https://www.racedepartment.com/threads/f1-2020-names-and-teams-changer.201082/page-8#post-3434864) found a temporary workaround, which is not ideal, but it is what it is.

Hopefully this information might help you find the issue and fix it :)
