### ISSUE TITLE
"Failed to find process"

### ISSUE THREAD

**Issue by EnriqueBanderas** [Electronics/F1NameChanger#9]
Hello, I run the app and then open F1 game on Steam. This happens both on DX 11 and 12, as per the screenshot after running "write to F1" I get "ERROR: Failed to find process, was the process stopped?" WARN: Stopping memory changer.

![bug](https://user-images.githubusercontent.com/81928959/113519604-9523a280-958d-11eb-82e6-d5f95a8ec462.PNG)

**Comment by Electronics** [comment]
It might be something to do with windows security settings. That sequence means it managed to find the process and when it tried to attach it failed. Try running the tool as admin? (Right Click-> Run as Administrator)

**Comment by EnriqueBanderas** [comment]
Thank you, I think that solved the issue. 
But now I have problem with the Regions as per the screenshot. Should I open a new issue?
Thank You so much

![region](https://user-images.githubusercontent.com/81928959/113521117-bb4e4000-9597-11eb-8ff2-a5f919936ab5.PNG)
